### ISSUE TITLE
CodeData削除に伴う、不要ファイルの削除

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer#31]
#### TASK
- [x] Board+CoreDataProperties.swift 削除
- [x] Card+CoreDataProperties.swift 削除
- [x] CardRelation+CoreDataProperties.swift 削除
