### ISSUE TITLE
おや | 複数削除できるUIに変更

### ISSUE THREAD

**Issue by luckyriverr** [HanaLucky/KPTer#83]
#### DONE
- ボード削除、カード削除のUIを以下のイメージで変更
  ![img_1874](https://cloud.githubusercontent.com/assets/16001636/14460656/972b0a42-00f9-11e6-93dd-dc61bd1948e9.jpg)

evernoteのノートブック削除のイメージで。
削除前は、確認。
消す前に確認を表示。
#### TASK
- [x] 調査 | 複数選択で削除可能なUIの機能の実現方法 #100 
- [x] UI | ボード一覧画面 | 複数削除のstoryboard作成 #101
- [x] View | ボード一覧画面 | 複数削除の実装 #102
- [x] UI | KPTエリア画面 | 複数削除のstoryboard作成 #103
- [x] View | KPTエリア画面 | 複数削除の実装 #104
#### REFERENCE

[UITableView の編集モードを利用してデータの削除や並び替えを行う](http://himaratsu.hatenablog.com/entry/tableview/editmode)
